holoman:
  name: Hello holoman
  how-long: 777

spring:
  main:
    allow-bean-definition-overriding: true
    # 아래와 같이 웹앱 타입을 NONE으로 설정할 경우 서블릿 컨테이너가 있더라도 None WebApp으로 실행되어 바로 종료됨
#    web-application-type: none
  # Spring profile 설정
  profiles:
    active: test
  output:
    ansi:
      enabled: always
  # H2 콘솔
  h2:
    console:
      enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
#      driver-class-name: com.mysql.cj.jdbc.Driver
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 4
#    url: jdbc:mysql://localhost:3306/springboot?useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:postgresql://localhost:5432/springboot?useSSL=false&allowPublicKeyRetrieval=true
    username: jaenyeong
    password: pass

server:
  # 무작위 포트 설정 (무작위 포트 번호 설정시 random 변수 사용 금지)
  # 권한이 없는 포트번호 또는 사용 중인 포트 번호 등을 선택할 수 있음
  #  port: 0
  port: 8443
  # [HTTPS - SSL 설정] 위 포트는 HTTPS
  ssl:
    # 다른 경로에 있는 경우 클래스패스로 위치 설정
    key-store: classpath:keystore.p12
    key-store-password: 123456
    keyStoreType: PKCS12
    keyAlias: spring
  http2:
    enabled: true

# undertow http 포트 설정
undertowPort: 8888
undertowInterface: 0.0.0.0

# 테스트 시 test/resources 경로에 있는 application.properties(yaml) 파일과 동일하게 맞춰줄 것
jaenyeong:
  name: jaenyeong
  # 미리 정의된 random 변수 사용 (무작위 포트번호 설정시 사용하면 안됨)
  # 권한이 없는 포트번호 또는 사용 중인 포트 번호 등을 선택할 수 있음
  # 랜덤 변수 사용시 파라미터 사이에 공백 주의
  age: ${random.int(1,100)}
#  age: 12345
  fullName: ${jaenyeong.name} Kim
  sessionTimeout: 25s
#  nullParam:

# 로깅 파일 출력 설정
logging:
  file:
    path: logs
  level:
    org:
      springframework: info
    com:
      jaenyeong: debug
  config: classpath:log4j2-spring.yaml
